# Generated by Django 5.2.17 on 2026-09-29 22:42
"""Migración inicial: crea los 6 modelos de la app `shop`.

Archivo GENERADO por `python manage.py makemigrations`. No se edita a mano: cualquier
cambio en `models.py` debe reflejarse con otro `makemigrations`, que crea una
migración nueva en vez de alterar esta.

Por qué importa: Django no usa `models.py` para tocar la base, usa estas
migraciones. Los modelos dicen cómo deberían ser las tablas; este archivo dice cómo
se llega a ellas. `python manage.py migrate` aplica estas operaciones en orden y
crea el esquema real en PostgreSQL.

Dos detalles de este archivo que explican el resto del proyecto:

- `dependencies` con `swappable_dependency(AUTH_USER_MODEL)`: las tablas de esta app
  tienen claves foráneas a `auth_user`, así que Django garantiza que el usuario se
  migra antes que `SavedCard`, `Order`, etc.
- El orden de las operaciones importa: `Product` se crea primero porque es destino
  de claves foráneas en `OrderItem`, `CartItem` y `SavedCard`. Django reordena
  automáticamente si hace falta al generar una migración nueva.

Las operaciones son `CreateModel`/`AddField`, no SQL: el SQL específico de
PostgreSQL lo genera Django al aplicarlas.

Para detectar cambios de modelos sin migrar: `makemigrations --check`.
"""

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Contenedor de las operaciones que crean el esquema inicial de `shop`."""

    # Marca esta migración como la primera de la app: `migrate` la usa como punto
    # de partida y no permite deshacerla con `migrate shop zero`.
    initial = True

    # Ver el docstring de la cabecera: sin esta dependencia, el orden de
    # creación de las tablas no está garantizado.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # El catálogo no depende de nada, así que es la primera que se crea.
    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emoji', models.CharField(blank=True, default='📦', max_length=8)),
                ('stock', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='MPCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id_mp', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_reference', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('mp_order_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='created', max_length=30)),
                ('payment_status', models.CharField(blank=True, max_length=30)),
                ('status_detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id_mp', models.CharField(max_length=64, unique=True)),
                ('first_six_digits', models.CharField(blank=True, max_length=6)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('expiration_month', models.PositiveSmallIntegerField()),
                ('expiration_year', models.PositiveSmallIntegerField()),
                ('payment_method_id', models.CharField(max_length=30)),
                ('payment_method_type', models.CharField(max_length=30)),
                ('payment_method_name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
